.. only:: html

   .. sidebar:: Summary

      :Version:		|version|
      :Release:		|release|
      :Date:		|today|
      :Status:		|dm_rn_status|
      :Contact:		|dm_rn_contact_obfuscated|
      :Organization:	|dm_rn_organization|
      :Address:		|dm_rn_address|
      :Copyright:	|dm_rn_copyright|
      :Authors:		|author|

			* |slz_obfuscated|

      :Abstract:	|dm_rn_abstract|
      :Target:		|dm_rn_target|

.. only:: latex

   .. sidebar:: Summary

      :Version:		|version|
      :Release:		|release|
      :Date:		|today|
      :Status:		|dm_rn_status|
      :Contact:		|dm_rn_contact_plain_text|
      :Organization:	|dm_rn_organization|
      :Address:		|dm_rn_address|
      :Copyright:	|dm_rn_copyright|
      :Authors:		|author|

			* |slz_plain_text|

      :Abstract:	|dm_rn_abstract|
      :Target:		|dm_rn_target|
