======================  ======================   ====================
Board                   Kernel Provider          Kernel Version
======================  ======================   ====================
qemuarmv6               linux-tqs                |linux_tqs_version|
tqma35                  linux-tqs                |linux_tqs_version|
======================  ======================   ====================

