.. Abstract:

.. |dm_abstract| replace:: This document has the Yocto tutorial of
   the TQ Systems Community BSP |version| which is a communty
   effort to start quick with it and learn the build and design
   workflow.


.. Target Audience:

.. |dm_target| replace:: users, developers and integrators
.. |dm_status| replace:: some mature, some in progress


.. Copyright:

.. |dm_copyright| replace:: Copyright |copy| 2013, |LPN| |---|
   all rights reserved. This work is licensed under a Creative Commons
   Attribution-ShareAlike 3.0 Unported License (`CC-BY-SA-3.0`_).
   See the file :download:`LICENSE <../../LICENSE>` that comes with
   the documentation.

.. |copy| unicode:: 0xA9 .. copyright sign
.. |LPN| unicode:: Li U+02013 Pro.Net
.. |---| unicode:: U+02014 .. em dash
   :trim:

.. Organization:

.. |dm_organization| replace:: |LPN|
.. |dm_address| replace:: Jena, Germany
.. |dm_contact_obfuscated| replace:: |slz_obfuscated|
.. |dm_contact_plain_text| replace:: |slz_plain_text|


.. Authors:

.. |slz| replace:: Stephan Linz
.. |slz_obfuscated| replace:: :email:`Stephan Linz <linz@li-pro.net>`
.. |slz_plain_text| replace:: Stephan Linz <linz@li-pro.net>


.. _`CC-BY-SA-3.0`: http://creativecommons.org/licenses/by-sa/3.0/
