.. Abstract:

.. |dm_abstract| replace:: This document has documentation of
   the TQ Systems Community BSP |version| which is a communty
   effort to improve TQ Systems board support based on different
   3rd party meta layer supports in OpenEmbedded and Yocto.

.. |dm_rn_abstract| replace:: This document has the release notes of
   the TQ Systems Community BSP |version| which is a communty
   effort to improve TQ Systems board support based on different
   3rd party meta layer supports in OpenEmbedded and Yocto.

.. |dm_yt_abstract| replace:: This document has the Yocto tutorial of
   the TQ Systems Community BSP |version| which is a communty
   effort to start quick with it and learn the build and design
   workflow.


.. Target Audience:

.. |dm_target| replace:: users, developers and integrators
.. |dm_status| replace:: some mature, some in progress

.. |dm_rn_target| replace:: |dm_target|
.. |dm_rn_status| replace:: |dm_status|

.. |dm_yt_target| replace:: |dm_target|
.. |dm_yt_status| replace:: |dm_status|


.. Copyright:

.. |dm_copyright| replace:: Copyright |copy| 2013, |LPN| |---|
   all rights reserved. This work is licensed under a Creative Commons
   Attribution-ShareAlike 3.0 Unported License (`CC-BY-SA-3.0`_).
   See the file |LICENSE| that comes with
   the documentation.

.. |copy| unicode:: 0xA9 .. copyright sign
.. |LPN| unicode:: Li U+02013 Pro.Net
.. |---| unicode:: U+02014 .. em dash
   :trim:

.. |dm_rn_copyright| replace:: |dm_copyright|

.. |dm_yt_copyright| replace:: |dm_copyright|


.. Organization:

.. |dm_organization| replace:: |publisher|
.. |dm_address| replace:: Jena, Germany
.. |dm_contact_obfuscated| replace:: |slz_obfuscated|
.. |dm_contact_plain_text| replace:: |slz_plain_text|

.. |dm_rn_organization| replace:: |dm_organization|
.. |dm_rn_address| replace:: |dm_address|
.. |dm_rn_contact_obfuscated| replace:: |dm_contact_obfuscated|
.. |dm_rn_contact_plain_text| replace:: |dm_contact_plain_text|

.. |dm_yt_organization| replace:: |dm_organization|
.. |dm_yt_address| replace:: |dm_address|
.. |dm_yt_contact_obfuscated| replace:: |dm_contact_obfuscated|
.. |dm_yt_contact_plain_text| replace:: |dm_contact_plain_text|


.. Authors:

.. |slz| replace:: Stephan Linz
.. |slz_obfuscated| replace:: :email:`Stephan Linz <linz@li-pro.net>`
.. |slz_plain_text| replace:: Stephan Linz <linz@li-pro.net>


.. _`CC-BY-SA-3.0`: http://creativecommons.org/licenses/by-sa/3.0/
